// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Compute: typeof import('./src/components/Compute.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GoodsList: typeof import('./src/components/content/goods/GoodsList.vue')['default']
    GoodsListItem: typeof import('./src/components/content/goods/GoodsListItem.vue')['default']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LoadingItem: typeof import('./src/components/common/loading/LoadingItem.vue')['default']
    MainTabBar: typeof import('./src/components/content/mainTabBar/MainTabBar.vue')['default']
    ManyButton: typeof import('./src/components/common/button/ManyButton.vue')['default']
    NavBar: typeof import('./src/components/common/navbar/NavBar.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    TabBar: typeof import('./src/components/common/tabbar/TabBar.vue')['default']
    TabBarItem: typeof import('./src/components/common/tabbar/TabBarItem.vue')['default']
    TabControl: typeof import('./src/components/content/tabControl/TabControl.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}

export { }
